language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t lbrf/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true lbrf/react-test npm test

after_success:
    - docker build -t lbrf/multi-client ./client
    - docker build -t lbrf/multi-nginx ./nginx
    - docker build -t lbrf/multi-server ./server
    - docker build -t lbrf/multi-worker ./worker
# log in the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# push to the docker 
    - docker push lbrf/multi-client
    - docker push lbrf/multi-nginx
    - docker push lbrf/multi-server
    - docker push lbrf/multi-worker 

deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-west-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-1-224660658189
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY